services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: cookieboy_db
      POSTGRES_USER: cookieboy
      POSTGRES_PASSWORD: Farruxovich12!
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8000"

volumes:
  pgdata:
