# Generated by Django 6.0.6 on 2026-07-09 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pantryitem',
            options={'ordering': ['expiration_date']},
        ),
        migrations.RemoveField(
            model_name='pantryitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pantryitem',
            name='ingredient_name',
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to='ingredients.ingredient'),
        ),
    ]
