# Generated by Django 6.0.6 on 2026-07-09 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('pantry', '0002_alter_pantryitem_options_remove_pantryitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='ingredient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to='ingredients.ingredient'),
            preserve_default=False,
        ),
    ]
